FROM opless/ubuntu-16.04-opencv-3.2.0
MAINTAINER Simon Waite <opless@gmail.com>

ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive

RUN pip install scipy
RUN pip install scikit-image
RUN pip install dlib
